import pytz

STATE_TIMEZONES = {
    'AL': 'America/Chicago',
    'AK': 'America/Anchorage',
    'AZ': 'America/Phoenix',
    'AR': 'America/Chicago',
    'CA': 'America/Los_Angeles',
    'CO': 'America/Denver',
    'CT': 'America/New_York',
    'DE': 'America/New_York',
    'FL': 'America/New_York',
    'GA': 'America/New_York',
    'HI': 'Pacific/Honolulu',
    'ID': 'America/Boise',
    'IL': 'America/Chicago',
    'IN': 'America/Indiana/Indianapolis',
    'IA': 'America/Chicago',
    'KS': 'America/Chicago',
    'KY': 'America/New_York',
    'LA': 'America/Chicago',
    'ME': 'America/New_York',
    'MD': 'America/New_York',
    'MA': 'America/New_York',
    'MI': 'America/Detroit',
    'MN': 'America/Chicago',
    'MS': 'America/Chicago',
    'MO': 'America/Chicago',
    'MT': 'America/Denver',
    'NE': 'America/Chicago',
    'NV': 'America/Los_Angeles',
    'NH': 'America/New_York',
    'NJ': 'America/New_York',
    'NM': 'America/Denver',
    'NY': 'America/New_York',
    'NC': 'America/New_York',
    'ND': 'America/Chicago',
    'OH': 'America/New_York',
    'OK': 'America/Chicago',
    'OR': 'America/Los_Angeles',
    'PA': 'America/New_York',
    'RI': 'America/New_York',
    'SC': 'America/New_York',
    'SD': 'America/Chicago',
    'TN': 'America/Chicago',
    'TX': 'America/Chicago',
    'UT': 'America/Denver',
    'VT': 'America/New_York',
    'VA': 'America/New_York',
    'WA': 'America/Los_Angeles',
    'WV': 'America/New_York',
    'WI': 'America/Chicago',
    'WY': 'America/Denver'
}

NEAREST_STATES = {
    'AL': ['MS', 'TN', 'GA'],
    'AK': ['WA', 'OR', 'CA'],
    'AZ': ['CA', 'NV', 'NM'],
    'AR': ['MO', 'TN', 'MS'],
    'CA': ['OR', 'NV', 'AZ'],
    'CO': ['WY', 'NE', 'KS'],
    'CT': ['NY', 'MA', 'RI'],
    'DE': ['MD', 'PA', 'NJ'],
    'FL': ['GA', 'AL', 'SC'],
    'GA': ['FL', 'AL', 'SC'],
    'HI': ['CA', 'NV', 'OR'],
    'ID': ['MT', 'WY', 'UT'],
    'IL': ['WI', 'IN', 'MO'],
    'IN': ['IL', 'OH', 'KY'],
    'IA': ['MN', 'WI', 'IL'],
    'KS': ['NE', 'MO', 'OK'],
    'KY': ['IN', 'OH', 'TN'],
    'LA': ['TX', 'AR', 'MS'],
    'ME': ['NH', 'MA', 'VT'],
    'MD': ['VA', 'PA', 'DE'],
    'MA': ['NH', 'RI', 'CT'],
    'MI': ['OH', 'IN', 'WI'],
    'MN': ['WI', 'IA', 'SD'],
    'MS': ['LA', 'AR', 'AL'],
    'MO': ['KS', 'NE', 'IA'],
    'MT': ['ID', 'WY', 'ND'],
    'NE': ['KS', 'MO', 'IA'],
    'NV': ['CA', 'OR', 'ID'],
    'NH': ['VT', 'ME', 'MA'],
    'NJ': ['PA', 'NY', 'DE'],
    'NM': ['AZ', 'TX', 'CO'],
    'NY': ['PA', 'NJ', 'CT'],
    'NC': ['SC', 'VA', 'TN'],
    'ND': ['SD', 'MT', 'MN'],
    'OH': ['IN', 'PA', 'KY'],
    'OK': ['TX', 'KS', 'AR'],
    'OR': ['WA', 'CA', 'NV'],
    'PA': ['NY', 'OH', 'NJ'],
    'RI': ['CT', 'MA', 'NY'],
    'SC': ['NC', 'GA', 'TN'],
    'SD': ['ND', 'MN', 'IA'],
    'TN': ['KY', 'VA', 'NC'],
    'TX': ['OK', 'LA', 'NM'],
    'UT': ['ID', 'WY', 'CO'],
    'VT': ['NH', 'MA', 'NY'],
    'VA': ['NC', 'MD', 'WV'],
    'WA': ['OR', 'ID', 'CA'],
    'WV': ['VA', 'OH', 'PA'],
    'WI': ['MN', 'IA', 'IL'],
    'WY': ['MT', 'SD', 'NE']
}